# Generated by Django 4.1 on 2022-11-09 00:01

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alunos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='aluno',
            name='foto',
            field=models.ImageField(blank=True, upload_to='fotos/%Y/%m/'),
        ),
        migrations.AlterField(
            model_name='aluno',
            name='data_vencimento_matricula',
            field=models.DateTimeField(default=datetime.datetime(2022, 12, 9, 0, 1, 39, 21728, tzinfo=datetime.timezone.utc)),
        ),
    ]
